
module.exports = {
	'aptamer': require('./aptamer'),
	'assembly-scar': require('./assembly-scar'),
	'biopolymer-junction': require('./biopolymer-junction'),
	'biopolymer-base': require('./biopolymer-base'),
	'biopolymer-amino-acid': require('./biopolymer-amino-acid'),
	'blunt-restriction-site': require('./blunt-restriction-site'),
	'cds': require('./cds'),
	'engineered-region': require('./engineered-region'),
	'helix': require('./helix'),
	'insulator': require('./insulator'),
	'mature-transcript-region': require('./mature-transcript-region'),
    'operator': require('./operator'),
	'origin-of-replication': require('./origin-of-replication'),
    'origin-of-transfer': require('./origin-of-transfer'),
	'poly-a': require('./poly-a'),
	'promoter': require('./promoter'),
	'protease-site': require('./protease-site'),
	'protein-stability': require('./protein-stability'),
	'protein-domain': require('./protein-domain'),
	'recombination-site': require('./recombination-site'),
    'res': require('./res'),
    'restriction-site': require('./restriction-site'),
	'ribonuclease-site': require('./ribonuclease-site'),
	'rna-stability': require('./rna-stability'),
	'stem-loop': require('./stem-loop'),
	'tag': require('./tag'),
    'terminator': require('./terminator'),
    'no-glyph-assigned': require('./no-glyph-assigned'),
    'unspecified': require('./unspecified')
}

